version: '3.1'

services:
     flyway:
          image: boxfuse/flyway:5.2.4
          command: -url=jdbc:mysql://db -schemas=monitoring_system -user=root -password= -connectRetries=60 migrate
          volumes:
               - $PWD/src/main/resources/db/migration:/flyway/sql
          depends_on:
               - db

     applifting:
          image: applifting
          build:
               context: ./
               dockerfile: Dockerfile
          volumes:
               - /data/applifting-rest-app
          container_name: applifting-rest-app
          depends_on:
               - db
               - flyway
          ports:
               - 8080:8080


     db:
          image: mysql:8.0
          restart: always
          ports:
          -   3308:3306
          environment:
               MYSQL_DATABASE: monitoring_system
               MYSQL_PASSWORD: ''
               MYSQL_ALLOW_EMPTY_PASSWORD: 1
          cap_add:
               - SYS_NICE